name: CI
on: [push, pull_request]
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y fontconfig
      - name: Checkout the adobe-fonts/source-code-pro
        uses: actions/checkout@v4
        with:
          repository: 'adobe-fonts/source-code-pro'
          ref: 'release'
          path: '/usr/share/fonts/source-code-pro'
      - name: Install the source-code-pro font
        run: |
          sudo rm -rf /usr/share/fonts/source-code-pro/.git
          sudo fc-cache -fv /usr/share/fonts/source-code-pro
      - uses: coursier/cache-action@v6
      - name: Run tests
        run: |
          sbt "+Test/compile; +test"
  docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: coursier/cache-action@v6
      - run: sbt site/run
